# Milestone 4.23: Understanding Array Shape, Dimensions, and Index Positions

**Learning Objectives:**
- Understand what shape and dimensions mean in NumPy
- Identify 1D, 2D, and higher-dimensional arrays
- Access elements using correct index positions
- Visualize how data is laid out in arrays
- Avoid common indexing mistakes

---

## Part 1: Why Shape and Indexing Matter

### Common Problems Without Understanding Shape:

- ❌ **IndexError** - Trying to access elements that don't exist
- ❌ **Wrong results** - Accessing wrong rows or columns
- ❌ **Confusion** - Misunderstanding data layout
- ❌ **Bugs** - Hard-to-diagnose errors in analysis

### What You'll Learn:

- ✅ How to read array shape
- ✅ What dimensions (ndim) represent
- ✅ How to safely access elements
- ✅ How to navigate rows and columns

**Think of shape as the blueprint of your data structure.**

In [5]:
# Import NumPy
import numpy as np

print("NumPy imported successfully!")
print(f"NumPy version: {np.__version__}")

NumPy imported successfully!
NumPy version: 2.3.5


---

## Part 2: Understanding Array Shape

**Shape** tells you the dimensions of your array—how many rows, columns, etc.

It's returned as a tuple.

### 1D Array Shape

In [2]:
# Create a 1D array
arr_1d = np.array([10, 20, 30, 40, 50])

print("1D Array:")
print(arr_1d)
print(f"\nShape: {arr_1d.shape}")
print(f"Explanation: (5,) means 5 elements in one dimension")
print(f"\nNote: The comma in (5,) indicates it's a 1D array, not a scalar")

1D Array:
[10 20 30 40 50]

Shape: (5,)
Explanation: (5,) means 5 elements in one dimension

Note: The comma in (5,) indicates it's a 1D array, not a scalar


In [ ]:
# Different sizes of 1D arrays
arr_small = np.array([1, 2, 3])
arr_medium = np.array([5, 10, 15, 20, 25])
arr_large = np.array([100, 200, 300, 400, 500, 600, 700, 800])

print("Different 1D Array Shapes:")
print(f"Small:  {arr_small} -> shape {arr_small.shape}")
print(f"Medium: {arr_medium} -> shape {arr_medium.shape}")
print(f"Large:  {arr_large} -> shape {arr_large.shape}")

print("\n💡 Pattern: 1D arrays have shape (n,) where n is the number of elements")

### 2D Array Shape

In [3]:
# Create a 2D array
arr_2d = np.array([[1, 2, 3],
                   [4, 5, 6]])

print("2D Array:")
print(arr_2d)
print(f"\nShape: {arr_2d.shape}")
print(f"Explanation: (2, 3) means 2 rows and 3 columns")
print(f"\nVisualization:")
print(f"  Row 0: [1, 2, 3]")
print(f"  Row 1: [4, 5, 6]")
print(f"  ↑")
print(f"  3 columns")

2D Array:
[[1 2 3]
 [4 5 6]]

Shape: (2, 3)
Explanation: (2, 3) means 2 rows and 3 columns

Visualization:
  Row 0: [1, 2, 3]
  Row 1: [4, 5, 6]
  ↑
  3 columns


In [ ]:
# Different 2D array shapes
arr_3x2 = np.array([[1, 2],
                    [3, 4],
                    [5, 6]])

arr_2x4 = np.array([[10, 20, 30, 40],
                    [50, 60, 70, 80]])

arr_4x3 = np.array([[1, 2, 3],
                    [4, 5, 6],
                    [7, 8, 9],
                    [10, 11, 12]])

print("Different 2D Array Shapes:")
print(f"\n3 rows × 2 columns:")
print(arr_3x2)
print(f"Shape: {arr_3x2.shape}")

print(f"\n2 rows × 4 columns:")
print(arr_2x4)
print(f"Shape: {arr_2x4.shape}")

print(f"\n4 rows × 3 columns:")
print(arr_4x3)
print(f"Shape: {arr_4x3.shape}")

print("\n💡 Pattern: 2D arrays have shape (rows, columns)")

### Accessing Shape Components

In [ ]:
arr = np.array([[1, 2, 3, 4],
                [5, 6, 7, 8],
                [9, 10, 11, 12]])

print("Array:")
print(arr)
print(f"\nShape: {arr.shape}")
print(f"\nNumber of rows: {arr.shape[0]}")
print(f"Number of columns: {arr.shape[1]}")
print(f"\nTotal elements: {arr.size}")
print(f"Calculation: {arr.shape[0]} × {arr.shape[1]} = {arr.size}")

---

## Part 3: Understanding Dimensions (ndim)

**ndim** tells you how many dimensions (axes) the array has.

- 1D array: like a list (one direction)
- 2D array: like a table (rows and columns)
- 3D array: like stacked tables (depth, rows, columns)

In [ ]:
# Different dimensional arrays
arr_1d = np.array([1, 2, 3, 4, 5])
arr_2d = np.array([[1, 2, 3], [4, 5, 6]])
arr_3d = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])

print("=" * 60)
print("DIMENSIONS COMPARISON")
print("=" * 60)

print("\n1D Array:")
print(arr_1d)
print(f"Shape: {arr_1d.shape}")
print(f"Dimensions (ndim): {arr_1d.ndim}")
print(f"Think: A single row of numbers")

print("\n2D Array:")
print(arr_2d)
print(f"Shape: {arr_2d.shape}")
print(f"Dimensions (ndim): {arr_2d.ndim}")
print(f"Think: A table with rows and columns")

print("\n3D Array:")
print(arr_3d)
print(f"Shape: {arr_3d.shape}")
print(f"Dimensions (ndim): {arr_3d.ndim}")
print(f"Think: Multiple tables stacked together")

print("\n" + "=" * 60)

In [ ]:
# Relationship between shape and ndim
arrays = [
    np.array([1, 2, 3]),
    np.array([[1, 2], [3, 4]]),
    np.array([[[1, 2]], [[3, 4]]])
]

print("Shape vs Dimensions:")
for i, arr in enumerate(arrays, 1):
    print(f"\nArray {i}:")
    print(f"  Shape: {arr.shape}")
    print(f"  Dimensions: {arr.ndim}")
    print(f"  Rule: ndim = number of values in shape tuple")

---

## Part 4: Indexing 1D Arrays

Accessing elements in 1D arrays is just like Python list indexing.

### Basic 1D Indexing

In [ ]:
arr = np.array([10, 20, 30, 40, 50])

print("Array:", arr)
print(f"Shape: {arr.shape} - 5 elements, indices 0-4")
print("\n--- POSITIVE INDEXING ---")

print(f"\narr[0] = {arr[0]}   <- First element")
print(f"arr[1] = {arr[1]}   <- Second element")
print(f"arr[2] = {arr[2]}   <- Third element")
print(f"arr[3] = {arr[3]}   <- Fourth element")
print(f"arr[4] = {arr[4]}   <- Fifth element (last)")

print("\n💡 Python indexing starts at 0, not 1!")

### Negative Indexing

In [ ]:
arr = np.array([10, 20, 30, 40, 50])

print("Array:", arr)
print("\n--- NEGATIVE INDEXING ---")

print(f"\narr[-1] = {arr[-1]}   <- Last element")
print(f"arr[-2] = {arr[-2]}   <- Second to last")
print(f"arr[-3] = {arr[-3]}   <- Third to last")
print(f"arr[-4] = {arr[-4]}   <- Fourth to last")
print(f"arr[-5] = {arr[-5]}   <- Fifth to last (first)")

print("\n💡 Negative indices count from the end backwards!")

### Index Visualization

In [ ]:
arr = np.array([10, 20, 30, 40, 50])

print("Index Mapping:")
print("\nPositive indices:")
print("Index:  0   1   2   3   4")
print("Value: 10  20  30  40  50")

print("\nNegative indices:")
print("Index: -5  -4  -3  -2  -1")
print("Value: 10  20  30  40  50")

print("\n💡 arr[0] and arr[-5] both give 10")
print(f"Verify: arr[0] = {arr[0]}, arr[-5] = {arr[-5]}")

---

## Part 5: Indexing 2D Arrays

2D arrays require TWO indices: `[row, column]`

**CRITICAL: Rows come FIRST, columns come SECOND!**

### Basic 2D Indexing

In [ ]:
matrix = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])

print("2D Array (Matrix):")
print(matrix)
print(f"\nShape: {matrix.shape} - 3 rows, 3 columns")
print(f"Valid row indices: 0, 1, 2")
print(f"Valid column indices: 0, 1, 2")

print("\n--- ACCESSING INDIVIDUAL ELEMENTS ---")
print(f"\nmatrix[0, 0] = {matrix[0, 0]}   <- Row 0, Column 0 (top-left)")
print(f"matrix[0, 1] = {matrix[0, 1]}   <- Row 0, Column 1")
print(f"matrix[0, 2] = {matrix[0, 2]}   <- Row 0, Column 2 (top-right)")
print(f"\nmatrix[1, 0] = {matrix[1, 0]}   <- Row 1, Column 0")
print(f"matrix[1, 1] = {matrix[1, 1]}   <- Row 1, Column 1 (center)")
print(f"matrix[1, 2] = {matrix[1, 2]}   <- Row 1, Column 2")
print(f"\nmatrix[2, 0] = {matrix[2, 0]}   <- Row 2, Column 0 (bottom-left)")
print(f"matrix[2, 1] = {matrix[2, 1]}   <- Row 2, Column 1")
print(f"matrix[2, 2] = {matrix[2, 2]}   <- Row 2, Column 2 (bottom-right)")

print("\n💡 Format: array[row, column] - NOT [column, row]!")

### Visual 2D Index Map

In [ ]:
matrix = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])

print("Visual Index Map:")
print("\n             Col 0  Col 1  Col 2")
print("           +------+------+------+")
print(f"Row 0      |  {matrix[0,0]}   |  {matrix[0,1]}   |  {matrix[0,2]}   |")
print("           +------+------+------+")
print(f"Row 1      |  {matrix[1,0]}   |  {matrix[1,1]}   |  {matrix[1,2]}   |")
print("           +------+------+------+")
print(f"Row 2      |  {matrix[2,0]}   |  {matrix[2,1]}   |  {matrix[2,2]}   |")
print("           +------+------+------+")

print("\nTo access value 5 (center):")
print(f"  Row: 1, Column: 1")
print(f"  Code: matrix[1, 1] = {matrix[1, 1]}")

### Accessing Entire Rows

In [ ]:
matrix = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])

print("Matrix:")
print(matrix)

print("\n--- ACCESSING ENTIRE ROWS ---")
print(f"\nRow 0: matrix[0] = {matrix[0]}")
print(f"Row 1: matrix[1] = {matrix[1]}")
print(f"Row 2: matrix[2] = {matrix[2]}")

print("\n💡 Omitting the column index gives you the entire row!")

### Accessing Entire Columns

In [ ]:
matrix = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])

print("Matrix:")
print(matrix)

print("\n--- ACCESSING ENTIRE COLUMNS ---")
print(f"\nColumn 0: matrix[:, 0] = {matrix[:, 0]}")
print(f"Column 1: matrix[:, 1] = {matrix[:, 1]}")
print(f"Column 2: matrix[:, 2] = {matrix[:, 2]}")

print("\n💡 The colon ':' means 'all rows', so [:, 0] means 'all rows, column 0'")

---

## Part 6: Common Mistakes and How to Avoid Them

### Mistake 1: Confusing Row and Column Order

In [4]:
matrix = np.array([[10, 20, 30],
                   [40, 50, 60]])

print("Matrix:")
print(matrix)
print(f"Shape: {matrix.shape} (2 rows, 3 columns)")

print("\n❌ WRONG - Thinking [column, row]:")
print("If trying to get 50 (row 1, col 1):")
print("  INCORRECT: matrix[1, 1] thinking it's [col 1, row 1]")

print("\n✅ CORRECT - Using [row, column]:")
print(f"  matrix[1, 1] = {matrix[1, 1]} (row 1, column 1)")

print("\n💡 Always: [ROW, COLUMN] - rows first!")

Matrix:
[[10 20 30]
 [40 50 60]]
Shape: (2, 3) (2 rows, 3 columns)

❌ WRONG - Thinking [column, row]:
If trying to get 50 (row 1, col 1):
  INCORRECT: matrix[1, 1] thinking it's [col 1, row 1]

✅ CORRECT - Using [row, column]:
  matrix[1, 1] = 50 (row 1, column 1)

💡 Always: [ROW, COLUMN] - rows first!


### Mistake 2: Going Out of Bounds

In [ ]:
arr = np.array([[1, 2, 3],
                [4, 5, 6]])

print("Array:")
print(arr)
print(f"\nShape: {arr.shape}")
print(f"Valid rows: 0 to {arr.shape[0]-1}")
print(f"Valid columns: 0 to {arr.shape[1]-1}")

print("\n✅ VALID INDICES:")
print(f"arr[0, 0] = {arr[0, 0]}")
print(f"arr[1, 2] = {arr[1, 2]}")

print("\n❌ INVALID INDICES (would cause errors):")
print("arr[2, 0]  - Row 2 doesn't exist!")
print("arr[0, 3]  - Column 3 doesn't exist!")
print("arr[2, 3]  - Both out of bounds!")

print("\n💡 Always check shape first to know valid ranges!")

### Mistake 3: Forgetting Zero-Based Indexing

In [ ]:
arr = np.array([100, 200, 300, 400, 500])

print("Array:")
print(arr)
print(f"Shape: {arr.shape} - 5 elements")

print("\n❌ THINKING (wrong):")
print("'If there are 5 elements, I can access arr[5]'")

print("\n✅ REALITY:")
print(f"First element: arr[0] = {arr[0]}")
print(f"Last element: arr[4] = {arr[4]}")
print(f"arr[5] would cause IndexError!")

print("\n💡 With n elements, valid indices are 0 to n-1!")

---

## Part 7: Practical Examples

### Example 1: Grade Table

In [ ]:
# Rows = Students, Columns = Test scores
grades = np.array([[85, 90, 88],  # Student 0
                   [92, 87, 95],  # Student 1
                   [78, 85, 80]]) # Student 2

print("Grade Table:")
print("           Test1  Test2  Test3")
print(f"Student 0:   {grades[0, 0]}     {grades[0, 1]}     {grades[0, 2]}")
print(f"Student 1:   {grades[1, 0]}     {grades[1, 1]}     {grades[1, 2]}")
print(f"Student 2:   {grades[2, 0]}     {grades[2, 1]}     {grades[2, 2]}")

print(f"\nShape: {grades.shape} (3 students, 3 tests)")

print("\n--- ACCESSING DATA ---")
print(f"Student 1's Test 2 score: grades[1, 1] = {grades[1, 1]}")
print(f"Student 2's all scores: grades[2] = {grades[2]}")
print(f"All students' Test 1 scores: grades[:, 0] = {grades[:, 0]}")

print("\n--- ANALYSIS ---")
print(f"Student 0 average: {grades[0].mean():.1f}")
print(f"Test 1 average: {grades[:, 0].mean():.1f}")

### Example 2: Sales Matrix

In [ ]:
# Rows = Stores, Columns = Days of week
sales = np.array([[120, 150, 180, 200, 250],  # Store A
                  [200, 180, 220, 240, 300],  # Store B
                  [100, 130, 140, 160, 180]]) # Store C

print("Weekly Sales Data:")
print("         Mon  Tue  Wed  Thu  Fri")
print(f"Store A: {sales[0, 0]:3d}  {sales[0, 1]:3d}  {sales[0, 2]:3d}  {sales[0, 3]:3d}  {sales[0, 4]:3d}")
print(f"Store B: {sales[1, 0]:3d}  {sales[1, 1]:3d}  {sales[1, 2]:3d}  {sales[1, 3]:3d}  {sales[1, 4]:3d}")
print(f"Store C: {sales[2, 0]:3d}  {sales[2, 1]:3d}  {sales[2, 2]:3d}  {sales[2, 3]:3d}  {sales[2, 4]:3d}")

print(f"\nShape: {sales.shape} (3 stores, 5 days)")

print("\n--- QUERIES ---")
print(f"Store B's Friday sales: sales[1, 4] = ${sales[1, 4]}")
print(f"Store A's weekly sales: sales[0] = {sales[0]}")
print(f"All stores' Monday sales: sales[:, 0] = {sales[:, 0]}")

print("\n--- INSIGHTS ---")
print(f"Best day for Store A: Day {sales[0].argmax()} (${sales[0].max()})")
print(f"Monday total all stores: ${sales[:, 0].sum()}")
print(f"Store B weekly average: ${sales[1].mean():.2f}")

---

## Part 8: Best Practices Summary

In [ ]:
print("="*70)
print("ARRAY SHAPE AND INDEXING - BEST PRACTICES")
print("="*70)

print("\n✅ ALWAYS DO:")
print("  1. Check shape BEFORE indexing")
print("     arr.shape tells you valid index ranges")
print("\n  2. Use [row, column] order for 2D arrays")
print("     NOT [column, row] - rows come first!")
print("\n  3. Remember zero-based indexing")
print("     First element is [0], not [1]")
print("\n  4. Understand dimensions (ndim)")
print("     ndim tells you how many indices you need")
print("\n  5. Use negative indices for end access")
print("     arr[-1] gets the last element")

print("\n❌ NEVER DO:")
print("  1. Assume index ranges without checking shape")
print("  2. Confuse [column, row] with [row, column]")
print("  3. Forget that indexing starts at 0")
print("  4. Try to access indices beyond array bounds")

print("\n💡 KEY FORMULAS:")
print("  Shape (n,)     → Valid indices: 0 to n-1")
print("  Shape (r, c)   → Valid rows: 0 to r-1, columns: 0 to c-1")
print("  Total elements → arr.size = arr.shape[0] × arr.shape[1] (for 2D)")

print("\n" + "="*70)

---

## ✅ Milestone 4.23 Complete!

### What You've Learned:

1. ✅ **Array Shape** - Understanding tuple format and what it represents
2. ✅ **Dimensions** - Interpreting ndim for 1D, 2D, and higher dimensions
3. ✅ **1D Indexing** - Accessing elements with single indices
4. ✅ **2D Indexing** - Using [row, column] notation correctly
5. ✅ **Zero-based** - First element is index 0
6. ✅ **Negative Indices** - Counting backwards from the end
7. ✅ **Rows and Columns** - Getting entire rows or columns
8. ✅ **Common Mistakes** - How to avoid IndexError and logic bugs

### Key Takeaways:

- 🎯 **Shape is your blueprint** - Check it first, always
- 🎯 **[row, column]** - NOT [column, row]
- 🎯 **Zero-based indexing** - arr[0] is first, arr[-1] is last
- 🎯 **ndim = len(shape)** - Dimensions match shape tuple length
- 🎯 **Valid range** - If shape is (n,), indices are 0 to n-1

### Next Steps:

After mastering shape and indexing, you'll learn:
- Array slicing (getting ranges of elements)
- Boolean indexing (filtering with conditions)
- Array reshaping
- Advanced indexing techniques

**You're now ready to navigate NumPy arrays safely and confidently!** 🚀